# -*- coding: utf-8 -*-
"""qatar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1taIpEgw5-BJhPvMyo3eaK_45WBcUF_qi
"""

import os
import random
import gradio as gr
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# ==============================================================================
# 1. الهوية البصرية وتصميم الصف العلوي للأقسام الأربعة للمنصة
# ==============================================================================
CBE_ORANGE_DARK = "#78350F" # برتقالي غامق جداً قاتم
CBE_ORANGE_MID = "#B45309"  # برتقالي غامق تراثي
CBE_ORANGE_LIGHT = "#D97706"# برتقالي أفتح نسبياً عند التحديد
CBE_NAVY = "#0A192F"        # أزرق ملكي عميق
CBE_BG = "#F8FAFC"          # خلفية ناعمة

CUSTOM_CSS = f"""
body, .gradio-container, .main {{
    background-color: {CBE_BG} !important;
    font-family: 'Cairo', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif !important;
}}

.header-center {{
    text-align: center !important;
    background: linear-gradient(135deg, rgba(10, 25, 47, 0.95) 0%, rgba(120, 53, 15, 0.90) 100%),
                url('https://images.unsplash.com/photo-1461360370896-922624d12aa1?q=80&w=1600&auto=format&fit=crop') !important;
    background-size: cover !important;
    background-position: center !important;
    backdrop-filter: blur(12px) !important;
    color: #FFFFFF !important;
    padding: 40px 20px !important;
    border-radius: 16px !important;
    border-bottom: 5px solid {CBE_ORANGE_MID} !important;
    box-shadow: 0 12px 35px rgba(0,0,0,0.35) !important;
    margin-bottom: 20px !important;
}}

.header-center h1 {{
    color: #FBBF24 !important;
    font-size: 26px !important;
    font-weight: 800 !important;
    margin-bottom: 12px !important;
    text-shadow: 0 2px 6px rgba(0,0,0,0.7) !important;
}}

.header-center h3 {{
    color: #F1F5F9 !important;
    font-size: 15px !important;
    font-weight: 500 !important;
    line-height: 1.6 !important;
    margin-bottom: 0px !important;
}}

/* شريط الأخبار المتحرك الانسيابي */
.ticker-wrap {{
    width: 100%;
    background: linear-gradient(90deg, {CBE_NAVY} 0%, {CBE_ORANGE_DARK} 100%);
    border-top: 2px solid {CBE_ORANGE_MID};
    border-bottom: 2px solid {CBE_ORANGE_MID};
    overflow: hidden;
    white-space: nowrap;
    box-shadow: 0 4px 10px rgba(0,0,0,0.2);
    margin-bottom: 25px;
    border-radius: 8px;
    direction: ltr !important;
}}

.ticker {{
    display: inline-block;
    padding-right: 100%;
    animation: marquee-infinite 55s linear infinite;
}}

.ticker-item {{
    display: inline-block;
    padding: 8px 30px;
    font-size: 14.5px;
    font-weight: bold;
    color: #FFFFFF !important;
    direction: rtl !important;
}}

@keyframes marquee-infinite {{
    0% {{ transform: translate(-100%, 0); }}
    100% {{ transform: translate(100%, 0); }}
}}

.lang-btn-style {{
    position: absolute !important;
    left: 20px !important;
    top: 20px !important;
    z-index: 9999 !important;
    background: linear-gradient(135deg, {CBE_ORANGE_MID} 0%, {CBE_ORANGE_DARK} 100%) !important;
    color: #FFFFFF !important;
    font-weight: bold !important;
    font-size: 13px !important;
    border: 2px solid #FBBF24 !important;
    border-radius: 10px !important;
    padding: 8px 18px !important;
    box-shadow: 0 4px 12px rgba(120, 53, 15, 0.4) !important;
    transition: all 0.3s ease !important;
}}

.lang-btn-style:hover {{
    background: {CBE_ORANGE_DARK} !important;
    transform: translateY(-2px);
}}

/* تخصيص التبويبات */
.tabs > .tab-nav, div[role="tablist"] {{
    display: flex !important;
    width: 100% !important;
    background: linear-gradient(135deg, {CBE_ORANGE_DARK} 0%, #451A03 100%) !important;
    border-radius: 12px !important;
    padding: 10px !important;
    box-shadow: 0 8px 25px rgba(120, 53, 15, 0.4) !important;
    margin-bottom: 25px !important;
    gap: 8px !important;
    border: 2px solid rgba(251, 191, 36, 0.4) !important;
}}

.tabs > .tab-nav button, div[role="tablist"] button {{
    flex: 1 !important;
    text-align: center !important;
    color: #FFFFFF !important;
    background-color: rgba(255, 255, 255, 0.06) !important;
    font-weight: bold !important;
    font-size: 14px !important;
    border: 1px solid rgba(255, 255, 255, 0.15) !important;
    border-radius: 8px !important;
    padding: 12px 10px !important;
    transition: all 0.3s ease !important;
}}

.tabs > .tab-nav button:hover {{
    background-color: {CBE_ORANGE_LIGHT} !important;
    color: #FFFFFF !important;
    border-color: #FBBF24 !important;
    transform: translateY(-2px);
}}

.tabs > .tab-nav button.selected, div[role="tablist"] button.selected {{
    background: linear-gradient(135deg, {CBE_ORANGE_LIGHT} 0%, #B45309 100%) !important;
    color: #FFFFFF !important;
    font-weight: 800 !important;
    border: 2px solid #FBBF24 !important;
    box-shadow: 0 4px 18px rgba(217, 119, 6, 0.7) !important;
}}

.primary-btn {{
    background: linear-gradient(135deg, {CBE_ORANGE_MID} 0%, {CBE_ORANGE_LIGHT} 100%) !important;
    color: #FFFFFF !important;
    font-weight: bold !important;
    font-size: 15px !important;
    border-radius: 8px !important;
    border: none !important;
    padding: 12px 24px !important;
    box-shadow: 0 4px 12px rgba(180, 83, 9, 0.4) !important;
    transition: all 0.3s ease !important;
}}

.primary-btn:hover {{
    background: linear-gradient(135deg, {CBE_ORANGE_DARK} 0%, {CBE_ORANGE_MID} 100%) !important;
    transform: translateY(-2px) !important;
    box-shadow: 0 6px 16px rgba(180, 83, 9, 0.6) !important;
}}

.danger-btn {{
    background: linear-gradient(135deg, #DC2626 0%, #991B1B 100%) !important;
    color: #FFFFFF !important;
    font-weight: bold !important;
    font-size: 14px !important;
    border-radius: 8px !important;
    border: none !important;
    padding: 10px 20px !important;
    box-shadow: 0 4px 12px rgba(220, 38, 38, 0.4) !important;
    transition: all 0.3s ease !important;
}}

.danger-btn:hover {{
    background: linear-gradient(135deg, #991B1B 0%, #7F1D1D 100%) !important;
    transform: translateY(-2px) !important;
}}

.export-btn {{
    background: linear-gradient(135deg, {CBE_NAVY} 0%, #1E293B 100%) !important;
    color: #FBBF24 !important;
    font-weight: bold !important;
    font-size: 14px !important;
    border: 1px solid {CBE_ORANGE_MID} !important;
    border-radius: 8px !important;
    padding: 10px 20px !important;
    margin-top: 12px !important;
    box-shadow: 0 2px 6px rgba(0,0,0,0.15) !important;
    transition: all 0.3s ease !important;
}}

.export-btn:hover {{
    background: {CBE_ORANGE_MID} !important;
    color: #FFFFFF !important;
}}

.footer-copyright {{
    text-align: center;
    color: #64748B;
    font-size: 13px;
    margin-top: 30px;
    border-top: 1px solid #E2E8F0;
    padding-top: 15px;
    font-weight: bold;
}}

.rtl-mode, .rtl-mode * {{
    direction: rtl !important;
    text-align: right !important;
}}
"""

ARAB_COUNTRIES = [
    "الدولة", "جمهورية مصر العربية", "دولة قطر", "المملكة العربية السعودية",
    "دولة الإمارات العربية المتحدة", "المملكة الأردنية الهاشمية",
    "المملكة المغربية", "الجمهورية التونسية", "الجمهورية الجزائرية الديمقراطية الشعبية",
    "سلطنة عمان", "مملكة البحرين", "دولة الكويت", "جمهورية العراق",
    "الجمهورية اللبنانية", "الجمهورية العربية السورية", "الجمهورية اليمنية",
    "جمهورية السودان", "ليبيا", "الجمهورية الإسلامية الموريتانية",
    "جمهورية جيبوتي", "جمهورية الصومال الفيدرالية", "اتحاد جزر القمر", "دولة فلسطين"
]

def get_colored_score_html(score):
    if score >= 80:
        return f"<span style='color: #16A34A; font-weight: bold;'>{score}% (أداء مرتفع 🟢)</span>"
    elif score >= 51:
        return f"<span style='color: #CA8A04; font-weight: bold;'>{score}% (أداء متوسط 🟡)</span>"
    else:
        return f"<span style='color: #DC2626; font-weight: bold;'>{score}% (فجوة هيكلية حرجة 🔴)</span>"

def calculate_aacri_platform(country_choice, ti_score, ed_score, hc_score, rf_score, cd_score, history_state):
    if country_choice == "الدولة":
        return "<div style='padding:20px; text-align:center; color:#991B1B; background:#FEF2F2; border-radius:10px; border:1px solid #F87171;'><b>⚠️ يرجى اختيار دولة عربية حقيقية من القائمة لتنفيذ التشخيص القياسي.</b></div>", None, pd.DataFrame(), history_state, gr.update(), gr.update(), gr.update()

    weights = {'TI': 0.20, 'ED': 0.15, 'HC': 0.30, 'RF': 0.20, 'CD': 0.15}
    final_score = (ti_score * weights['TI']) + (ed_score * weights['ED']) + (hc_score * weights['HC']) + (rf_score * weights['RF']) + (cd_score * weights['CD'])
    final_score = round(final_score, 2)

    score_html_colored = get_colored_score_html(final_score)

    if final_score >= 80:
        diagnosis = "🟢 جاهزية متقدمة للغاية نحو السيادة الرقمية والابتكار المستدام وتفعيل 'المبدع المعزز'."
        detailed_diag = f"🟢 **جاهزية متقدمة ومستدامة:** إجمالي المؤشر المركب {score_html_colored}. تعكس هذه النتيجة تفوقاً هيكلياً في بيئة العمل، ورأس مال بشري مؤهل للتعامل مع التقنيات التوليدية، وبنية تقنية متطورة تتيح قيادة التحالفات الإقليمية وتوطين النماذج الثقافية الرقمية بكفاءة عالية بما يضمن صون الأمن الثقافي."
    elif final_score >= 51:
        diagnosis = "🟡 جاهزية متوسطة، تتطلب تدخلات استباقية لمعالجة الاختناقات الهيكلية."
        detailed_diag = f"🟡 **جاهزية متوسطة تتطلب تدخلاً استباقياً:** إجمالي المؤشر المركب {score_html_colored}. تشير المؤشرات إلى توازن نسبي يواجه بعض الاختناقات الهيكلية في سلاسل القيمة أو التشريعات التنظيمية، مما يستوجب حزم تحفيزية وبرامج إعادة تأهيل (Upskilling & Reskilling) لردم الفجوات القائمة."
    else:
        diagnosis = "🔴 وجود فجوة ذكية هيكلية تستوجب تفعيل محاكي السياسات ولوحة دعم اتخاذ القرار فوراً."
        detailed_diag = f"🔴 **فجوة ذكية هيكلية حرجة:** إجمالي المؤشر المركب {score_html_colored}. توضح القراءة الحالية وجود اختناقات عميقة في البنية التحتية والبيئة التشريعية ورأس المال البشري، مما يستوجب تفعيل محاكي السياسات ولوحة التطعيم الثقافي لدعم 'المبدع المعزز' وتفادي الاستلاب الخوارزمي."

    if history_state is None:
        history_state = []

    entry = {
        "الدولة": country_choice,
        "المؤشر المركب (AACRI)": final_score,
        "البنية التقنية (20%)": ti_score,
        "الديناميكيات الاقتصادية (15%)": ed_score,
        "رأس المال البشري (30%)": hc_score,
        "البيئة التنظيمية والتشريعية (20%)": rf_score,
        "المحددات الثقافية والهوياتية (15%)": cd_score,
        "التقييم المنظومي": diagnosis
    }

    updated = False
    for i, item in enumerate(history_state):
        if item["الدولة"] == country_choice:
            history_state[i] = entry
            updated = True
            break
    if not updated:
        history_state.append(entry)

    df_history = pd.DataFrame(history_state)
    if not df_history.empty:
        df_history = df_history.sort_values(by="المؤشر المركب (AACRI)", ascending=False).reset_index(drop=True)

    categories = ['البنية التقنية (20%)', 'الديناميكيات الاقتصادية (15%)', 'رأس المال البشري (30%)', 'البيئة التنظيمية والتشريعية (20%)', 'المحددات الثقافية والهوياتية (15%)']
    scores_list = [ti_score, ed_score, hc_score, rf_score, cd_score]

    fig = go.Figure()
    fig.add_trace(go.Scatterpolar(
        r=scores_list,
        theta=categories,
        fill='toself',
        name=country_choice,
        line_color=CBE_ORANGE_MID
    ))
    fig.update_layout(
        polar=dict(radialaxis=dict(visible=True, range=[0, 100])),
        paper_bgcolor="#FFFFFF",
        font=dict(family="Cairo", size=13)
    )

    result_html = f"""
    <div dir="rtl" style="text-align: right; background: #FFFFFF; padding: 25px; border-radius: 12px; border: 1.5px solid {CBE_ORANGE_MID}; line-height: 1.9; box-shadow: 0 4px 15px rgba(0,0,0,0.05);">
      <h3 style="color: {CBE_NAVY}; font-weight: bold; margin-bottom: 12px;">📊 نتائج التشخيص المنظومي للدولة العربية (إطار AACRI - 69 متغيراً)</h3>
      <p style="font-size: 15px; margin-bottom: 8px;"><b>النموذج الخاضع للتشخيص:</b> <span style="color: {CBE_NAVY}; font-weight: bold;">{country_choice}</span></p>
      <p style="font-size: 16px; margin-bottom: 12px;"><b>القيمة المركبة لمؤشر الجاهزية الذكية (AACRI):</b> <span style="font-size: 18px;">{score_html_colored}</span></p>
      <div style="background: {CBE_BG}; padding: 16px; border-radius: 8px; border-right: 5px solid {CBE_ORANGE_MID}; margin-top: 10px;">
        <p style="margin: 0 0 8px 0; font-weight: bold; color: {CBE_NAVY};">التقييم التشخيصي والتفصيل المنظومي:</p>
        <p style="margin: 0; color: #1E293B; font-size: 14.5px;">{detailed_diag}</p>
      </div>
    </div>
    """

    country_choices = [item["الدولة"] for item in history_state]
    default_selected = country_choices[0] if country_choices else country_choice

    return (
        result_html, fig, df_history, history_state,
        gr.update(choices=country_choices, value=default_selected),
        gr.update(choices=country_choices, value=default_selected if country_choices else None),
        gr.update(choices=country_choices, value=default_selected if country_choices else None)
    )

def delete_country_from_record(country_to_delete, history_state):
    if not history_state or not country_to_delete:
        return "<div style='padding:15px; text-align:center;'>لا توجد بيانات لحذفها أو لم يتم اختيار دولة.</div>", pd.DataFrame(), history_state, gr.update(choices=[], value=None), gr.update(choices=[], value=None), gr.update(choices=[], value=None)

    history_state = [item for item in history_state if item["الدولة"] != country_to_delete]
    df_history = pd.DataFrame(history_state)
    if not df_history.empty:
        df_history = df_history.sort_values(by="المؤشر المركب (AACRI)", ascending=False).reset_index(drop=True)

    country_choices = [item["الدولة"] for item in history_state]
    default_selected = country_choices[0] if country_choices else None

    msg = f"<div style='padding:15px; background:#F0FDF4; border:1px solid #16A34A; border-radius:8px; color:#166534;'><b>✅ تم حذف سجل دولة ({country_to_delete}) بنجاح وتحديث القوائم والنتائج تلقائياً.</b></div>"

    return msg, df_history, history_state, gr.update(choices=country_choices, value=default_selected), gr.update(choices=country_choices, value=default_selected), gr.update(choices=country_choices, value=default_selected)

simulated_results_dict = {}

def run_policy_simulator(sim_country, base_aacri, scenario_type, var1_tech, var2_eco, var3_hc, var4_reg, var5_cult, history_state):
    if not sim_country or sim_country == "الدولة":
        return "<div style='padding:20px; text-align:center;'><b>⚠️ يرجى اختيار دولة عربية صحيحة أولاً.</b></div>"

    country_item = None
    if history_state:
        for item in history_state:
            if item["الدولة"] == sim_country:
                country_item = item
                base_aacri = item["المؤشر المركب (AACRI)"]
                break

    combined_boost = (var1_tech * 0.25) + (var2_eco * 0.15) + (var3_hc * 0.3) + (var4_reg * 0.2) + (var5_cult * 0.1)

    if scenario_type.startswith("📉"):
        simulated_val = max(0.0, base_aacri * 0.90)
        analysis_text = f"تحذير هيكلي لـ ({sim_country}): استمرار الركود وغياب الإصلاحات سيؤدي إلى تفاقم فجوة الإحلال الخوارزمي واندثار المهن الثقافية بنسبة تصل إلى 32%."
        action_plan = "التدخل الفوري لإيقاف التدهور وإعادة تخصيص ميزانيات طارئة وتفعيل لوحة التطعيم الثقافي."
    elif scenario_type.startswith("📊"):
        simulated_val = min(100.0, base_aacri * (1 + (combined_boost * 0.0022)))
        analysis_text = f"تقدم ملحوظ لـ ({sim_country}): نجاح تدريجي في ترشيد استخدام الأدوات التوليدية، دعم مهارات 'المبدع المعزز'، وتقليص الفجوة المهنية."
        action_plan = "توسيع برامج التدريب المستمر (Upskilling & Reskilling) واعتماد حزم تحفيزية."
    else:
        simulated_val = min(100.0, base_aacri * (1 + (combined_boost * 0.0042)))
        analysis_text = f"نجاح استراتيجي فائق لـ ({sim_country}): تحقيق السيادة الرقمية الكاملة، توطين النماذج اللغوية الثقافية العربية، وتفعيل دور المبدع كشريك إبداعي مهيمن."
        action_plan = "قيادة التحالفات التقنية الإقليمية وإطلاق المنصات السحابية المفتوحة وتأمين الأمن الثقافي."

    simulated_val = round(simulated_val, 2)
    delta = round(simulated_val - base_aacri, 2)
    sim_colored_html = get_colored_score_html(simulated_val)

    if base_aacri >= 80:
        deep_level_analysis = """
        <div style='background: #F0FDF4; padding: 14px; border-radius: 8px; border-right: 4px solid #16A34A; margin-top: 10px;'>
          <p style='margin: 0 0 6px 0; font-weight: bold; color: #166534;'>🔬 إضافات تحليلية عميقة (مستوى الأداء المرتفع 80+):</p>
          <p style='margin: 0; color: #14532D; font-size: 14px;'>الدولة تتمتع بامتصاص صدمات تقنية عالية؛ لذا فإن السياسات المستهدفة يجب أن تركز على قيادة المعايير العالمية للوسم المائي وحماية الهوية عبر خوارزميات مفتوحة المصدر وتصدير المعرفة الإبداعية الإقليمية دون الاكتفاء بالتوطين المحلي.</p>
        </div>
        """
    elif base_aacri >= 51:
        deep_level_analysis = """
        <div style='background: #FEFCE8; padding: 14px; border-radius: 8px; border-right: 4px solid #CA8A04; margin-top: 10px;'>
          <p style='margin: 0 0 6px 0; font-weight: bold; color: #854D0E;'>🔬 إضافات تحليلية عميقة (مستوى الأداء المتوسط 51-79):</p>
          <p style='margin: 0; color: #713F12; font-size: 14px;'>يتضح وجود تفاوت بين البنية التقنية ورأس المال البشري؛ يتطلب الأمر التركيز على سد الفجوة بين مخرجات التعليم العالي واحتياجات الاقتصاد البرتقالي، وتكثيف الشراكات العابرة للحدود لتجاوز الاختناقات التشريعية المؤقتة.</p>
        </div>
        """
    else:
        deep_level_analysis = """
        <div style='background: #FEF2F2; padding: 14px; border-radius: 8px; border-right: 4px solid #DC2626; margin-top: 10px;'>
          <p style='margin: 0 0 6px 0; font-weight: bold; color: #991B1B;'>🔬 إضافات تحليلية عميقة (مستوى الفجوات الهيكلية الحرجة <50):</p>
          <p style='margin: 0; color: #7F1D1D; font-size: 14px;'>الدولة تواجه هشاشة في سلاسل القيمة الإبداعية؛ تتطلب المحاكاة هنا تدخلات عاجلة وحزم طوارئ استثمارية لدعم البنية التحتية الرقمية الأساسية واحتواء قطاع الاقتصاد غير الرسمي قبل تفاقم الاستلاب الخوارزمي.</p>
        </div>
        """

    new_sim_box = f"""
    <div dir="rtl" style="text-align: right; background: #FFFFFF; padding: 22px; border-radius: 12px; border: 1.5px solid {CBE_ORANGE_MID}; margin-bottom: 18px; box-shadow: 0 4px 12px rgba(0,0,0,0.06);">
      <h3 style="color: {CBE_NAVY}; font-weight: bold; margin-bottom: 8px;">📈 محاكاة دولة: {sim_country} | السيناريو: {scenario_type}</h3>
      <p style="font-size: 15px; margin-bottom: 8px;"><b>القيمة المتوقعة للمؤشر بعد المحاكاة:</b> {sim_colored_html} (صافي التغير: <span style="font-weight: bold;">{delta:+.2f}</span>)</p>
      <div style="background: {CBE_BG}; padding: 12px; border-radius: 8px; border-right: 4px solid {CBE_ORANGE_MID}; margin-top: 10px;">
        <p style="margin-bottom: 6px;"><b>🔬 التحليل القياسي:</b> {analysis_text}</p>
        <p style="margin: 0 0 8px 0; color: {CBE_ORANGE_MID}; font-weight: bold;">🛠️ خطة التحرك الاستباقية: {action_plan}</p>
      </div>
      {deep_level_analysis}
    </div>
    """

    simulated_results_dict[sim_country] = new_sim_box
    output_html = "".join(simulated_results_dict.values())
    return output_html

decision_results_dict = {}

def generate_dynamic_decision_report(selected_country, history_state):
    global decision_results_dict
    if not history_state or not selected_country or selected_country == "الدولة":
        return "<div style='padding:20px; text-align:center; color:#0A192F; background:#FFFFFF; border-radius:10px; border:1px solid #B45309;'><b>⚠️ يرجى أولاً إدخال بيانات الدولة وحساب مؤشر AACRI في القسم الأول لتوليد التوصيات المخصصة.</b></div>"

    country_data = None
    for item in history_state:
        if item["الدولة"] == selected_country:
            country_data = item
            break

    if not country_data:
        return f"<div style='padding:20px; text-align:center;'>لم يتم العثور على بيانات مسجلة لـ {selected_country}.</div>"

    score = country_data["المؤشر المركب (AACRI)"]
    score_colored_str = get_colored_score_html(score)

    if score >= 80:
        recommendations = f"""
        <li><b>تعزيز ريادة الابتكار الإقليمي:</b> الاستفادة من جاهزية ({selected_country}) المرتفعة ({score_colored_str}) لتصدير النماذج اللغوية الثقافية العربية الموطنة.</li>
        <li><b>الحوكمة المتقدمة للذكاء الاصطناعي:</b> قيادة الجهود التشريعية الإقليمية لإلزام الشركات الكبرى (Big Tech) بمعايير الوسم المائي (Watermarking) والشفافية.</li>
        <li><b>دعم الاقتصاد البرتقالي:</b> التوسع في توظيف استراتيجية المحيط الأزرق (BOS) في السياحة الثقافية الافتراضية.</li>
        """
        deep_third_analysis = """
        <div style='background: #F0FDF4; padding: 14px; border-radius: 8px; border-right: 4px solid #16A34A; margin-top: 12px;'>
          <p style='margin: 0 0 6px 0; font-weight: bold; color: #166534;'>🛡️ إضافات تحليلية عميقة لدعم القرار (مستوى الأداء المرتفع 80+):</p>
          <p style='margin: 0; color: #14532D; font-size: 14px;'>توصي منظومة القرار بإنشاء "مجلس سيادي أعلى للذكاء الاصطناعي والثقافة" لربط مخرجات البحث والتطوير بالأسواق الإقليمية، وتأسيس صناديق رأس مال مخاطر متخصصة في تمويل المشاريع الثقافية العابرة للحدود.</p>
        </div>
        """
    elif score >= 51:
        recommendations = f"""
        <li><b>ردم الفجوة التقنية والبشرية:</b> إطلاق حزم برامج إعادة التأهيل السريع (Upskilling & Reskilling) لدعم القوى العاملة وتمكين المبدع المعزز في ({selected_country}).</li>
        <li><b>سد الاختناقات الهيكلية:</b> تحفيز الشراكات بين المؤسسات الأكاديمية والقطاع الإبداعي لدمج التعليم البيني.</li>
        <li><b>توثيق التراث الرقمي:</b> تسريع وتيرة أرشفة الأصول التراثية عبر قواعد بيانات ثلاثية الأبعاد (3D Archives).</li>
        """
        deep_third_analysis = """
        <div style='background: #FEFCE8; padding: 14px; border-radius: 8px; border-right: 4px solid #CA8A04; margin-top: 12px;'>
          <p style='margin: 0 0 6px 0; font-weight: bold; color: #854D0E;'>🛡️ إضافات تحليلية عميقة لدعم القرار (مستوى الأداء المتوسط 51-79):</p>
          <p style='margin: 0; color: #713F12; font-size: 14px;'>تتطلب صانعة القرار هنا تفعيل "حاضنات الأعمال الإبداعية المشتركة" وتوجيه الدعم المالي نحو القطاعات الأكثر عرضة للإحلال الخوارزمي، مع صياغة تشريعات مرنة تحمي حقوق المبدعين البشريين بالتوازي مع دمج الأدوات التوليدية.</p>
        </div>
        """
    else:
        recommendations = f"""
        <li><b>التدخل الاستباقي العاجل:</b> معالجة الاختناقات الهيكلية الحادة في البنية التقنية ورأس المال البشري لـ ({selected_country}).</li>
        <li><b>الاستفادة من التكامل الوظيفي:</b> توجيه الشراكات الإقليمية للاستفادة من البنى التحتية المتقدمة (مثل نموذج الوفرة السيادية) لسد الفجوة الرقمية.</li>
        <li><b>احتواء الاقتصاد غير الرسمي:</b> دمج الأنشطة الإبداعية المستترة عبر أدوات الحصر الرقمي البديلة ولوحة اتخاذ القرار.</li>
        """
        deep_third_analysis = """
        <div style='background: #FEF2F2; padding: 14px; border-radius: 8px; border-right: 4px solid #DC2626; margin-top: 12px;'>
          <p style='margin: 0 0 6px 0; font-weight: bold; color: #991B1B;'>🛡️ إضافات تحليلية عميقة لدعم القرار (مستوى الفجوات الهيكلية الحرجة <50):</p>
          <p style='margin: 0; color: #7F1D1D; font-size: 14px;'>تفرض الضرورة القصوى استدعاء إطار "التكامل الوظيفي الإقليمي" ونقل الخبرات التقنية والبنية التحتية من الدول الشقيقة المتقدمة، مع إطلاق برامج طارئة لمكافحة الاستلاب الخوارزمي وحماية الحرف التراثية المهددة بالاندثار.</p>
        </div>
        """

    new_box = f"""
    <div dir="rtl" style="text-align: right; background: #FFFFFF; padding: 22px; border-radius: 12px; border: 1.5px solid {CBE_ORANGE_MID}; margin-bottom: 18px; box-shadow: 0 4px 12px rgba(0,0,0,0.06);">
      <h3 style="color: {CBE_NAVY}; font-weight: bold; margin-bottom: 8px;">🛡️ تقرير وتوصيات دولة: {selected_country} (المؤشر المركب: {score_colored_str})</h3>
      <ul style="margin: 0 0 10px 0; padding-right: 20px; line-height: 1.8; color: #1E293B;">
        {recommendations}
      </ul>
      {deep_third_analysis}
    </div>
    """

    decision_results_dict[selected_country] = new_box
    output_html = "".join(decision_results_dict.values())
    return output_html

def generate_executive_summary_report(history_state):
    if not history_state:
        return "<div style='padding:25px; text-align:center; color:#0A192F; background:#FFFFFF; border-radius:12px; border:1px solid #B45309;'><b>📂 لا توجد بيانات مسجلة كافية حتى الآن. يرجى إدخال تشخيص دولة واحدة على الأقل في القسم الأول لتوليد التقرير التنفيذي الموحد.</b></div>"

    df = pd.DataFrame(history_state)
    top_row = df.iloc[0] if not df.empty else None
    top_country = top_row["الدولة"] if top_row is not None else "غير محدد"
    top_score = top_row["المؤشر المركب (AACRI)"] if top_row is not None else 0
    top_score_colored = get_colored_score_html(top_score)

    countries_summary = ""
    for idx, row in df.iterrows():
        s = row['المؤشر المركب (AACRI)']
        s_colored = get_colored_score_html(s)

        ti_val = row['البنية التقنية (20%)']
        ed_val = row['الديناميكيات الاقتصادية (15%)']
        hc_val = row['رأس المال البشري (30%)']
        rf_val = row['البيئة التنظيمية والتشريعية (20%)']
        cd_val = row['المحددات الثقافية والهوياتية (15%)']

        if s >= 80:
            analytic_desc = "تفوق هيكلي وجاهزية متقدمة في تبني السياسات الذكية وتفعيل المبدع المعزز."
            axes_deep_analysis = f"""
            <ul style="margin: 8px 0 0 0; padding-right: 18px; font-size: 13.5px; color: #1E293B; line-height: 1.7;">
              <li><b>البنية التقنية ({ti_val}%):</b> دلالة متقدمة تعكس سعة فائقة في شبكات البيانات وتوطين النماذج اللغوية، ولها أثر إيجابي مباشر في تحقيق السيادة الرقمية والارتباط التشابكي مع رأس المال البشري.</li>
              <li><b>الديناميكيات الاقتصادية ({ed_val}%):</b> مساهمة قوية للاقتصاد البرتقالي وصادرات إبداعية عالية، تشابكها وثيق مع البيئة التشريعية لحماية العوائد الاستثمارية.</li>
              <li><b>رأس المال البشري ({hc_val}%):</b> ركيزة مرجحة (30%) تؤكد كفاءة عالية في هندسة الأوامر وتمكين المبدع المعزز، مع ارتباط طردي بمنظومة الابتكار.</li>
              <li><b>البيئة التنظيمية والتشريعية ({rf_val}%):</b> أطر حوكمة متطورة وأدوات وسم مائي دقيقة تمنع الاحتكار الرقمي وتضمن استقرار السوق الإبداعي.</li>
              <li><b>المحددات الثقافية والهوياتية ({cd_val}%):</b> أرشفة تراثية ثلاثية الأبعاد ممتازة وحماية للأمن الثقافي والتمثيل الخوارزمي للهوية الوطنية.</li>
            </ul>
            """
        elif s >= 51:
            analytic_desc = "توازن نسبى مع وجود حاجة ماسة لتدخلات هيكلية استباقية وبرامج إعادة التأهيل."
            axes_deep_analysis = f"""
            <ul style="margin: 8px 0 0 0; padding-right: 18px; font-size: 13.5px; color: #1E293B; line-height: 1.7;">
              <li><b>البنية التقنية ({ti_val}%):</b> تتطلب تحديثاً لتدفق البيانات وتوسيع نطاق السحابات الرقمية لتفادي الاختناقات التشغيلية وسد الفجوة التقنية.</li>
              <li><b>الديناميكيات الاقتصادية ({ed_val}%):</b> مساهمة متوسطة للاقتصاد الإبداعي تستوجب حزم تحفيزية وضخ استثمار مخاطر لتعزيز سلاسل القيمة.</li>
              <li><b>رأس المال البشري ({hc_val}%):</b> حاجة ملحة لبرامج إعادة تأهيل سريعة (Upskilling) لسد الفجوة بين المخرجات الأكاديمية ومتطلبات المبدع المعزز.</li>
              <li><b>البيئة التنظيمية والتشريعية ({rf_val}%):</b> تشريعات قائمة بحاجة لتطوير وتفعيل آليات حماية الملكية الفكرية المشتركة مع تطبيقات الذكاء الاصطناعي.</li>
              <li><b>المحددات الثقافية والهوياتية ({cd_val}%):</b> جهود تراثية مقبولة تتطلب عمقاً أكبر في أرشفة المحتوى الرقمي العربي وحمايته من الاستلاب الخوارزمي.</li>
            </ul>
            """
        else:
            analytic_desc = "فجوة هيكلية عميقة تستوجب إصلاحات جذرية عاجلة وتفعيل أدوات التفكير المنظومي."
            axes_deep_analysis = f"""
            <ul style="margin: 8px 0 0 0; padding-right: 18px; font-size: 13.5px; color: #1E293B; line-height: 1.7;">
              <li><b>البنية التقنية ({ti_val}%):</b> قصور هيكلي في البنية التحتية وسرعات الإنترنت يستوجب تدخلات طارئة وتكامل وصيغة تكامل وظيفي إقليمي.</li>
              <li><b>الديناميكيات الاقتصادية ({ed_val}%):</b> اقتصاد برتقالي ضعف ومساهمة محدودة تقابله نسبة عالية من الاقتصاد غير الرسمي غير الحصري.</li>
              <li><b>رأس المال البشري ({hc_val}%):</b> فجوة حرجة في المهارات التوليدية والتعليم البيني تستدعي خطط طوارئ تعليمية وفورية.</li>
              <li><b>البيئة التنظيمية والتشريعية ({rf_val}%):</b> غياب الأطر التشريعية الناظمة لحقوق المبدع في عصر الخوارزميات مما يعرض الأمن الثقافي لمخاطر عالية.</li>
              <li><b>المحددات الثقافية والهوياتية ({cd_val}%):</b> تراجع في التمثيل الخوارزمي للهوية المحلية وضعف في الأرشفة الرقمية يتطلب تفعيل لوحة التطعيم الثقافي فوراً.</li>
            </ul>
            """

        countries_summary += f"""
        <li style="margin-bottom: 22px; line-height: 1.8; background: #F8FAFC; padding: 16px; border-radius: 10px; border: 1px solid #E2E8F0;">
            <b>{row['الدولة']}</b> — المؤشر المركب: {s_colored} — التقييم: {row['التقييم المنظومي']}<br>
            <span style="color: #475569; font-size: 14px; display: inline-block; margin-top: 4px;">💡 <b>تحليل منظومي وصفي:</b> {analytic_desc}</span>
            <div style="margin-top: 8px; border-top: 1px dashed #CBD5E1; padding-top: 8px;">
              <p style="margin: 0 0 4px 0; font-weight: bold; color: {CBE_NAVY}; font-size: 13.5px;">🔍 التحليل العميق والشامل للمحاور الخمسة الكبرى:</p>
              {axes_deep_analysis}
            </div>
        </li>
        """

    report_html = f"""
    <div dir="rtl" style="text-align: right; background: #FFFFFF; padding: 30px; border-radius: 14px; border: 2px solid {CBE_ORANGE_MID}; line-height: 1.9; box-shadow: 0 6px 20px rgba(0,0,0,0.08);">
      <div style="text-align: center; border-bottom: 2px solid {CBE_ORANGE_MID}; padding-bottom: 15px; margin-bottom: 25px;">
        <h2 style="color: {CBE_NAVY}; font-weight: 800; margin: 0;">📑 التقرير التنفيذي الموحد لسياسات الصناعات الثقافية والإبداعية العربية</h2>
        <p style="color: #64748B; font-size: 14.5px; margin-top: 6px;">ملخص استراتيجي موجه للقيادات العليا وصناع القرار - بناءً على مخرجات الدراسة المنهجية والتفكير المنظومي (AACRI)</p>
      </div>

      <div style="background: {CBE_BG}; padding: 18px; border-radius: 10px; border-right: 5px solid {CBE_ORANGE_MID}; margin-bottom: 25px;">
        <h4 style="color: {CBE_NAVY}; margin-top: 0;">🏆 مؤشرات الأداء العام والريادة الإقليمية:</h4>
        <p style="margin-bottom: 8px;">الدولة المتصدرة حالياً في مؤشر الجاهزية الذكية هي: <span style="font-weight: bold;">{top_country}</span> بقيمة مركبة تبلغ {top_score_colored}.</p>
        <p style="margin: 0;">إجمالي الدول الخاضعة للتشخيص والتحليل المنظومي حتى الآن: <b>{len(df)} دولة عربية</b>.</p>
      </div>

      <h4 style="color: {CBE_NAVY}; margin-bottom: 12px;">📋 ملخص نتائج التشخيص التراكمي للدول والتحليل العميق للمحاور:</h4>
      <ul style="margin-bottom: 25px; padding-right: 0; list-style-type: none;">
        {countries_summary}
      </ul>

      <div style="background: #FFFBEB; padding: 22px; border-radius: 12px; border: 1.5px solid #FCD34D; margin-bottom: 15px;">
        <h4 style="color: #92400E; margin-top: 0; font-size: 17px;">🌳 إطار شجرة قرارات نقاط الرفع المنظومي (Meadows Leverage Points Framework):</h4>
        <p style="margin-bottom: 12px; color: #78350F; font-size: 15px;">بناءً على نتائج التشخيص، تعتمد المنظومة في هيكلة قراراتها الاستراتيجية للقيادات على مستويات التأثير لدونيلا ميدوز مرتبة انسيابياً من الأقل للأعلى تأثيرًا لضمان معالجة الفجوات:</p>
        <ul style="margin: 0; padding-right: 20px; line-height: 1.9; color: #78350F;">
          <li><b>1. المعلمات والميزانيات (Parameters - أقل تأثيراً):</b> تعديل نسب الإنفاق المباشر وموازنات دعم التدريب وهندسة الأوامر الرقمية للكوادر الإبداعية.</li>
          <li><b>2. تدفق المعلومات وحلقات التغذية الراجعة (Information Flows):</b> توفير قواعد بيانات مرجعية ومنصات حصر رقمية للمهن الإبداعية لتقليل التشوهات المعلوماتية واحتواء الاقتصاد غير الرسمي.</li>
          <li><b>3. القواعد والحوكمة (Rules):</b> تشريع أطر الملكية الفكرية المشتركة وحماية حقوق المبدع المعزز (Augmented Creator) في بيئة الذكاء الاصطناعي.</li>
          <li><b>4. أهداف النظام (Goals):</b> توجيه السياسات الوطنية نحو تحقيق السيادة الرقمية والأمن الثقافي الإقليمي المستدام.</li>
          <li><b>5. النماذج الفكرية والعقليات (Paradigms - الأشد تأثيراً):</b> ترسيخ مفهوم "الاقتصاد البرتقالي والبنفسجي" كركيزة أساسية ورؤية استراتيجية للتنمية المستدامة في عصر الذكاء الاصطناعي.</li>
        </ul>
      </div>
    </div>
    """
    return report_html

def notify_under_construction():
    gr.Info("🚧 Notice: The English version is currently under construction and will be available soon.")

def plot_structural_hierarchy():
    axes_names = [
        'البنية التقنية (20%)',
        'الديناميكيات الاقتصادية (15%)',
        'رأس المال البشري (30%)',
        'البيئة التنظيمية والتشريعية (20%)',
        'المحددات الثقافية والهوياتية (15%)'
    ]
    weights = [20, 15, 30, 20, 15]

    fig = px.bar(
        x=axes_names,
        y=weights,
        text=weights,
        labels={'x': 'المحاور الخمسة الكبرى للمؤشر', 'y': 'الوزن النسبي (%)'},
        title="توزيع الأوزان النسبية لمحاور مؤشر الجاهزية الذكية (AACRI) وفق التحليل الهرمي AHP (69 متغيراً)",
        color=weights,
        color_continuous_scale="Oranges"
    )
    fig.update_traces(texttemplate='%{text}% من الوزن النسبي', textposition='outside')
    fig.update_layout(
        paper_bgcolor="#FFFFFF",
        plot_bgcolor="#FFFFFF",
        font=dict(family="Cairo", size=13),
        margin=dict(t=50, b=30, l=30, r=30),
        yaxis=dict(range=[0, 35])
    )
    return fig

with gr.Blocks(theme=gr.themes.Soft(), css=CUSTOM_CSS) as demo:

    comparison_history_state = gr.State(value=[])

    with gr.Row():
        lang_btn = gr.Button("English (Under Construction 🚧)", elem_classes=["lang-btn-style"])
        lang_btn.click(fn=notify_under_construction, inputs=[], outputs=[])

    gr.Markdown(f"""
    <div class="header-center">
    <h1>نموذج مقترح لتطوير منصة منظومة القرار المتكاملة للسياسات الثقافية والإبداعية العربية</h1>
    <h3>ضمن مخرجات دراسة بحثية مقاربة منهجية لتطوير مهن الصناعات الثقافية والإبداعية العربية في عصر الذكاء الاصطناعي بمنظور التفكير المنظومي</h3>
    </div>
    """)

    gr.HTML("""
    <div class="ticker-wrap">
      <div class="ticker">
        <span class="ticker-item">🏛️ ضمن مخرجات دراسة بحثية مقاربة منهجية لتطوير مهن الصناعات الثقافية والإبداعية العربية في عصر الذكاء الاصطناعي بمنظور التفكير المنظومي</span>
        <span class="ticker-item">| 📊 مؤشر الجاهزية الذكية المركب (AACRI): الهيكل الهرمي الخماسي والمتغيرات الـ 69</span>
        <span class="ticker-item">| 📈 محاكي السياسات الاستشرافي العميق لاختبار السيناريوهات الاستراتيجية (Multiple Regression)</span>
        <span class="ticker-item">| 🛡️ لوحة دعم اتخاذ القرار ولوحة التطعيم الثقافي (Cultural Grafting Canvas)</span>
        <span class="ticker-item">| 📑 التقرير التنفيذي الموحد للقيادات العليا وإطار دونيلا ميدوز لنقاط الرفع | جميع الحقوق محفوظة للدراسة البحثية</span>
      </div>
    </div>
    """)

    with gr.Tabs(elem_classes=["rtl-mode", "tabs"]) as main_tabs:

        with gr.TabItem("📊 تشخيص مؤشر الجاهزية (AACRI)", id="tab1"):
            gr.Markdown("### 🌐 التشخيص القياسي لمؤشر الجاهزية الذكية للصناعات الثقافية والإبداعية (AACRI)")
            gr.Markdown("إمكانية التشخيص للدول العربية المختارة مع تسجيل وثبات النتائج في الجدول التراكمي وإدارة السجلات.")

            with gr.Row():
                with gr.Column(scale=1):
                    country_sel = gr.Dropdown(choices=ARAB_COUNTRIES, value=ARAB_COUNTRIES[0], label="اختر الدولة العربية")
                    ti_slider = gr.Slider(minimum=0, maximum=100, value=68, step=1, label="1️⃣ البنية التقنية (وزن 20%)")
                    ed_slider = gr.Slider(minimum=0, maximum=100, value=70, step=1, label="2️⃣ الديناميكيات الاقتصادية (وزن 15%)")
                    hc_slider = gr.Slider(minimum=0, maximum=100, value=72, step=1, label="3️⃣ رأس المال البشري (وزن 30%)")
                    rf_slider = gr.Slider(minimum=0, maximum=100, value=65, step=1, label="4️⃣ البيئة التنظيمية والتشريعية (وزن 20%)")
                    cd_slider = gr.Slider(minimum=0, maximum=100, value=82, step=1, label="5️⃣ المحددات الثقافية والهوياتية (وزن 15%)")

                    calc_aacri_btn = gr.Button("🚀 احسب وسجل قياس الدولة", elem_classes=["primary-btn"])

                with gr.Column(scale=2):
                    aacri_output_html = gr.HTML(value="<div style='padding:20px; text-align:center; color:#0A192F; background:#FFFFFF; border-radius:10px; border:1px solid #B45309;'><b>📊 يرجى اختيار الدولة وضبط درجات المحاور ثم الضغط على زر الحساب.</b></div>")
                    aacri_radar_plot = gr.Plot(label="🎯 التمثيل الراداري للمحاور الخمسة الكبرى")

            gr.Markdown("---")
            gr.Markdown("### 📋 قائمة ترتيب الدول العربية")

            with gr.Row(elem_classes=["rtl-mode"]):
                delete_country_dropdown = gr.Dropdown(choices=[], label="اختر دولة من السجل لحذفها", interactive=True)
                delete_country_btn = gr.Button("🗑️ حذف الدولة المحددة من السجل", elem_classes=["danger-btn"])

            delete_msg_output = gr.HTML(value="")

            comparison_table = gr.Dataframe(label="قائمة ترتيب الدول العربية", headers=["الدولة", "المؤشر المركب (AACRI)", "البنية التقنية (20%)", "الديناميكيات الاقتصادية (15%)", "رأس المال البشري (30%)", "البيئة التنظيمية والتشريعية (20%)", "المحددات الثقافية والهوياتية (15%)", "التقييم المنظومي"], interactive=False)

            export_btn_tab1 = gr.Button("📥 تصدير وطباعة تقرير القسم الأول (PDF / طباعة)", elem_classes=["export-btn"])
            export_btn_tab1.click(fn=None, inputs=[], outputs=[], js="() => { window.print(); }")

            with gr.Accordion("📂 استعراض المصفوفة الإجرائية للمحاور الرئيسة والأبعاد والـ 69 متغيراً للمؤشر (AACRI)", open=False):
                gr.Markdown("""
                * **البنية التقنية (وزن 20%):** يضم مؤشرات سعة وتدفق البيانات الضخمة، سرعات الإنترنت عريض الباند، وتوطين النماذج اللغوية الكبيرة (LLMs).
                * **الديناميكيات الاقتصادية (وزن 15%):** يضم مساهمة الاقتصاد البرتقالي في الناتج المحلي، الصادرات الإبداعية، وصفقات رأس المال المخاطر (VC).
                * **رأس المال البشري (وزن 30%):** يضم نسب التدريب المعتمد في هندسة الأوامر (Prompt Engineering) وبرامج إعادة التأهيل (Reskilling & Upskilling) وتمكين 'المبدع المعزز'.
                * **البيئة التنظيمية والتشريعية (وزن 20%):** يضم تشريعات الملكية الفكرية المشتركة، أطر المسؤولية (Liability)، وآليات الوسم المائي (Watermarking).
                * **المحددات الثقافية والهوياتية (وزن 15%):** يضم نسبة المحتوى الرقمي المتاح بالعربية، أرشفة التراث ثلاثي الأبعاد (3D Archives), ومؤشرات الأمن الثقافي.
                """)
                hierarchy_plot = gr.Plot(value=plot_structural_hierarchy(), label="📊 المخطط البياني لتوزيع أوزان الهيكل الخماسي للمؤشر")

            gr.HTML(f'<div class="footer-copyright">جميع الحقوق محفوظة للدراسة البحثية</div>')

        with gr.TabItem("📈 محاكي السياسات (Policy Simulator)", id="tab2"):
            gr.Markdown("### 🔬 محاكي السياسات الاستشرافي والمتابعة التراكمية للسيناريوهات")
            gr.Markdown("استشراف أثر التدخلات الاستثمارية والتقنية عبر النمذجة القياسية ومتغيرات التحفيز الاستراتيجي.")

            with gr.Row():
                with gr.Column(scale=1):
                    sim_country_sel = gr.Dropdown(choices=[ARAB_COUNTRIES[0]], value=ARAB_COUNTRIES[0], label="اختر الدولة للمحاكاة")
                    base_aacri_input = gr.Slider(minimum=30, maximum=100, value=68.5, step=0.5, label="قيمة المؤشر الافتراضي الحالي (إن لم تكن مسجلة)")
                    scenario_dropdown = gr.Dropdown(
                        choices=[
                            "📉 السيناريو التشاؤمي (غياب التدخل وضعف الاستثمار)",
                            "📊 السيناريو المعتدل / التفاؤلي (استثمارات تقليدية تدريجية)",
                            "🚀 السيناريو الطموح / الاستباقي (إصلاحات هيكلية شاملة وسيادة تقنية)"
                        ],
                        value="📊 السيناريو المعتدل / التفاؤلي (استثمارات تقليدية تدريجية)",
                        label="اختر السيناريو الاستراتيجي"
                    )
                    var1_tech = gr.Slider(minimum=0, maximum=50, value=20, step=1, label="1️⃣ نسبة الزيادة في البنية التقنية وتوطين النماذج (%)")
                    var2_eco = gr.Slider(minimum=0, maximum=50, value=15, step=1, label="2️⃣ نسبة الزيادة في الديناميكيات الاقتصادية والصادرات (%)")
                    var3_hc = gr.Slider(minimum=0, maximum=50, value=15, step=1, label="3️⃣ نسبة الزيادة في رأس المال البشري والتعليم البيني (%)")
                    var4_reg = gr.Slider(minimum=0, maximum=50, value=10, step=1, label="4️⃣ معدل تطوير البيئة التنظيمية والتشريعية (%)")
                    var5_cult = gr.Slider(minimum=0, maximum=50, value=25, step=1, label="5️⃣ نسبة التوسع في المحددات الثقافية والهوياتية (%)")

                    run_sim_btn = gr.Button("📋 إضافة وتثبيت سيناريو الدولة", elem_classes=["primary-btn"])

                with gr.Column(scale=2):
                    sim_output_box = gr.HTML(value="<div style='padding:20px; text-align:center; color:#0A192F; background:#FFFFFF; border-radius:10px; border:1px solid #B45309;'><b>📈 قم بضبط الدولة والسيناريو ومتغيرات التحفيز واضغط على زر الإضافة لتثبيت ومتابعة السيناريوهات هنا.</b></div>")
                    export_btn_tab2 = gr.Button("📥 تصدير وطباعة تقرير المحاكي (PDF / طباعة)", elem_classes=["export-btn"])
                    export_btn_tab2.click(fn=None, inputs=[], outputs=[], js="() => { window.print(); }")

            run_sim_btn.click(
                fn=run_policy_simulator,
                inputs=[sim_country_sel, base_aacri_input, scenario_dropdown, var1_tech, var2_eco, var3_hc, var4_reg, var5_cult, comparison_history_state],
                outputs=[sim_output_box]
            )

            gr.HTML(f'<div class="footer-copyright">جميع الحقوق محفوظة للدراسة البحثية</div>')

        with gr.TabItem("🛡️ لوحة دعم اتخاذ القرار", id="tab3"):
            gr.Markdown("### 🛡️ لوحة دعم اتخاذ القرار ولوحة التطعيم الثقافي (Cultural Grafting Canvas)")
            gr.Markdown("استعراض وتثبيت التوصيات المخصصة لكل دولة مختارة بديناميكية تمنع التكرار وتدعم السيادة الرقمية.")

            with gr.Row():
                with gr.Column(scale=1):
                    decision_country_sel = gr.Dropdown(choices=[ARAB_COUNTRIES[0]], value=ARAB_COUNTRIES[0], label="اختر الدولة لاستعراض وإضافة التوصيات")
                    generate_decision_btn = gr.Button("📋 إضافة وتثبيت توصيات الدولة المختارة", elem_classes=["primary-btn"])
                with gr.Column(scale=2):
                    decision_output_box = gr.HTML(value="<div style='padding:20px; text-align:center; color:#0A192F; background:#FFFFFF; border-radius:10px; border:1px solid #B45309;'><b>🛡️ يرجى اختيار الدولة المسجلة والضغط على زر الإضافة لتثبيت التوصيات هنا.</b></div>")
                    export_btn_tab3 = gr.Button("📥 تصدير وطباعة تقرير لوحة القرار والتوصيات التراكمية (PDF / طباعة)", elem_classes=["export-btn"])
                    export_btn_tab3.click(fn=None, inputs=[], outputs=[], js="() => { window.print(); }")

            generate_decision_btn.click(
                fn=generate_dynamic_decision_report,
                inputs=[decision_country_sel, comparison_history_state],
                outputs=[decision_output_box]
            )

            gr.HTML(f'<div class="footer-copyright">جميع الحقوق محفوظة للدراسة البحثية</div>')

        with gr.TabItem("📑 التقرير التنفيذي الموحد", id="tab4"):
            gr.Markdown("### 📑 أداة تصدير التقرير التنفيذي الموحد لسياسات الصناعات الثقافية والإبداعية")
            gr.Markdown("ملخص استراتيجي شامل يدمج نتائج التشخيص الوصفي، التحليل العميق للمحاور، وشجرة نقاط الرفع لدونيلا ميدوز في تقرير موحد جاهز للعرض على القيادات العليا.")

            with gr.Row():
                refresh_report_btn = gr.Button("🔄 تحديث وتوليد التقرير التنفيذي الموحد بناءً على البيانات المدخلة", elem_classes=["primary-btn"])

            exec_report_output = gr.HTML(value="<div style='padding:25px; text-align:center; color:#0A192F; background:#FFFFFF; border-radius:12px; border:1px solid #B45309;'><b>📂 اضغط على زر التحديث أعلاه لتوليد التقرير التنفيذي الموحد بناءً على تشخيص الدول في القسم الأول.</b></div>")

            export_btn_tab4 = gr.Button("📥 تصدير وطباعة التقرير التنفيذي الموحد (PDF / طباعة رسمية للقيادات)", elem_classes=["export-btn"])
            export_btn_tab4.click(fn=None, inputs=[], outputs=[], js="() => { window.print(); }")

            refresh_report_btn.click(
                fn=generate_executive_summary_report,
                inputs=[comparison_history_state],
                outputs=[exec_report_output]
            )

            gr.HTML(f'<div class="footer-copyright">جميع الحقوق محفوظة للدراسة البحثية</div>')

    calc_aacri_btn.click(
        fn=calculate_aacri_platform,
        inputs=[country_sel, ti_slider, ed_slider, hc_slider, rf_slider, cd_slider, comparison_history_state],
        outputs=[aacri_output_html, aacri_radar_plot, comparison_table, comparison_history_state, decision_country_sel, sim_country_sel, delete_country_dropdown]
    )

    delete_country_btn.click(
        fn=delete_country_from_record,
        inputs=[delete_country_dropdown, comparison_history_state],
        outputs=[delete_msg_output, comparison_table, comparison_history_state, decision_country_sel, sim_country_sel, delete_country_dropdown]
    )

# التشغيل الآمن المتوافق مع المنصات السحابية (Streamlit / Hugging Face)
if __name__ == "__main__":
    import os
    port = int(os.environ.get("PORT", 7860))
    demo.launch(server_name="0.0.0.0", server_port=port, share=False)
